<a href="https://colab.research.google.com/github/Sanchithedau/Data_Science_Lab_SE_A_18/blob/main/Experiment%203/%20Determinant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("Enter the 9 elements for the 3x3 matrix, separated by spaces or newlines:")
matrix_elements = []
for i in range(3):
    row = list(map(float, input(f"Enter row {i+1} elements: ").split()))
    if len(row) != 3:
        raise ValueError("Each row must contain exactly 3 elements.")
    matrix_elements.extend(row)

# Reshape the list into a 3x3 NumPy array
matrix = np.array(matrix_elements).reshape(3, 3)

print("\nYour 3x3 Matrix:")
print(matrix)

Enter the 9 elements for the 3x3 matrix, separated by spaces or newlines:
Enter row 1 elements: 1 0 0
Enter row 2 elements: 0 1 0
Enter row 3 elements: 0 0 1

Your 3x3 Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np

# Assuming 'matrix' from the previous cell is available
determinant = np.linalg.det(matrix)

print(f"\nThe determinant of the matrix is: {determinant}")


The determinant of the matrix is: 1.0
